name: Deploy application

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Caching modules
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-de-derde-kamer-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-de-derde-kamer-cache-
      - name: Install dependencies
        run: npm install
      - name: Run Lint
        run:  npm run lint
      - name: Run Prettier
        run:  npm run format
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy to S3
        run: npm run deploy
      - name: Invalidate cache
        run: npm run invalidateCache
